### ISSUE TITLE
Edit Transcript to add bold for speakers

### ISSUE THREAD

**Issue by hzoo** [hzoo/maintainersanonymous.com#13]
> Oh yeah and if the topic sounds interesting please give the podcast a listen 😛 - would love to hear your feedback or of other people to talk with!

Files are in this folder: https://github.com/hzoo/maintainersanonymous.com/tree/master/src/pages

I'd like to change the format

<img width="638" alt="Screen Shot 2019-10-05 at 1 25 45 PM" src="https://user-images.githubusercontent.com/588473/66258468-b37bc880-e773-11e9-9ac5-6eb7a13daeba.png">

so that it's bolded. The markdown changes are just adding `**Name**` to all the speaker names (without bolding when it's used in the text). You can do some text manipulation to do this.

In Sublime/VSCode/editors: you can do a multiple cursor selection or just a find replace. Example: Find `Henry: ` and replace with `**Henry**: ` to make **Henry**:

Example diff/change: https://github.com/hzoo/maintainersanonymous.com/pull/12/commits/26b53a739e961e4d23c379f70c9c2ef6b493e306

- [x] boundaries.md #16
- [x] freedom.md #15
- [x] games.md #17
- [x] getting-old.md #17
- [x] growing-old.md (done by me)
- [x] preservation.md
- [x] speedrunning.md (done by me)
- [ ] standards.md
- [x] uptime.md
- [ ] value.md

Can just comment below if you want to take one of these files (do one at a time)

**Comment by oscar8a** [comment]
I'll do freedom.md

**Comment by alejandra-gonzalez** [comment]
I'll do boundaries.md

**Comment by Crammers** [comment]
Ill take games.md

**Comment by ghost** [comment]
I'll do uptime.md

**Comment by gregorycode** [comment]
Hello. I'll do preservation.md

**Comment by hzoo** [comment]
Moving the repo to hope in source, so don't need to maintain multiple https://github.com/hzoo/hopeinsource.com/tree/master/ma-episodes
